# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1ec665f729c67a94e417a76129fabba9b4186fd3a01e964857ed47c80a90577c6c15048951b5ad22a28aa0f034444b871fe3ef5a664a21650d60de1c09fbcbb

test:
  secret_key_base: aa0a56e5f5a9221e486161e48f918ecc75a570dacedc81601ce84819ccbcaf49c9302d4f6b2c1faf7bbd0c1e0fc3050c9fb0ceeb95eebe426b53f46764e43f3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
